### ISSUE TITLE
建议增加重试上传和删除release的功能

### ISSUE THREAD

**Issue by uubulb** [nICEnnnnnnnLee/action-gitee-release#3]
1. 默认的action runner到gitee连接并不是特别好，偶尔会出现某个文件上传失败的问题，增加一个重试上传的功能可以免去重试整个工作流的麻烦
2. Gitee有配额限制，免费版一个仓库的附件限额只有1GB，很容易就超了。可以增加一个删除release的功能，仅保留最新的几个release

加这些功能有助于提升用户体验，不过似乎也不太适合全做到一起，可以酌情考虑一下

**Comment by nICEnnnnnnnLee** [comment]
删除功能不在考虑范围内
